name: Scrapy Spider Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Daily at 4:00 UTC (9:30 AM IST)

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scrapy spider
      run: scrapy crawl table_spider

    - name: Upload output.json
      uses: actions/upload-artifact@v4
      with:
        name: scraped-data
        path: output.json

    - name: Upload output.csv
      uses: actions/upload-artifact@v4
      with:
        name: scraped-csv
        path: output.csv

    - name: Upload debug HTML (optional)
      uses: actions/upload-artifact@v4
      with:
        name: debug-html
        path: cloud_response.html
